### PR TITLE
UE Missing Props

### PR DESCRIPTION
**Pull request by TalmizAhmed**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://ue-missing-props--aem-boilerplate-forms--adobe-rnd.hlx.live/

### CODE REVIEW

**Comment by nit23uec** [comment]
I hope you've verified their behavior in runtime also.

**Comment by TalmizAhmed** [comment]
@nit23uec Yes, you can verify the modified changes applied here: https://experience-stage.adobe.com/#/@aemformsdev/aem/editor/canvas/cb5d-152-58-239-14.ngrok-free.app/content/testsite/index.html

**Comment by nit23uec** [comment]
Pls rename to title for all supported form components. Form button, form image are still left.

**Comment by TalmizAhmed** [comment]
Changed them. I had intentionally not added Hide title to them as they are not supported in core components. Looks like I forgot to change the label.

**Review by nit23uec — APPROVED** [review]

**Pull request merged**
