### PR TITLE
FORMS-14491:RestButton validation on wizard

### PR DESCRIPTION
**Pull request by pranay-tippa**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After:https://resetbutton--aem-boilerplate-forms--adobe-rnd.hlx.live/

### CODE REVIEW

**Comment by ravise5** [comment]
@pranay-tippa Can you fix the eslint issues in the test file?

**Comment by ravise5** [comment]
Lets rename this file to `wizard.spec.js` , going ahead we will add all wizard related tests here.

**Review by ravise5 — CHANGES_REQUESTED** [review]
Please check the above comments

**Comment by ravise5** [comment]
Let's rename this file to `wizard.spec.js' we will add all wizard related tests here.

**Review by vdua — APPROVED** [review]

**Review by ravise5 — APPROVED** [review]

**Pull request merged**
