### PR TITLE
Replace OOTB browser messages with constant strings

### PR DESCRIPTION
**Pull request by ravise5**
Context:

  The OOTB browser messages cannot be localised as they are not part of our code and these messages often vary from 
  browser to browser. 
  In this PR these browser validity messages are replaced by a set of fixed strings maintained in the _`constants.js`_ file , 
  so that OOTB error messages are consistent across browsers and localisable.
  
  cc: @vdua 

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://dev--aem-boilerplate-forms--adobe-rnd.hlx.page/
- After: https://errormessage--aem-boilerplate-forms--adobe-rnd.hlx.page/

### CODE REVIEW

**Comment by vdua** [comment]
shouldn't this be added along with the localisation change to keep the context why it was done.

**Comment by ravise5** [comment]
> shouldn't this be added along with the localisation change to keep the context why it was done.

Wanted to keep things less cluttered. Localisation PR is not yet merged, I'll raise it once this is merged.

**Comment by amit-mnnit** [comment]
> Context:
> 
> The OOTB browser messages cannot be localised as they are not part of our code and these messages often vary from browser to browser. In this PR these browser validity messages are replaced by a set of fixed strings maintained in the _`constants.js`_ file , so that OOTB error messages are consistent across browsers and localisable.
> 
> cc: @vdua
> 
> Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
> 
> Fix #
> 
> Test URLs:
> 
> * Before: https://dev--aem-boilerplate-forms--adobe-rnd.hlx.page/
> * After: https://errormessage--aem-boilerplate-forms--adobe-rnd.hlx.page/

According to the documentation, `element.validationMessage` returns the localized message. 
please check https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/validationMessage

**Review by vdua — APPROVED** [review]

**Comment by vdua** [comment]
> According to the documentation, element.validationMessage returns the localized message.
please check https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/validationMessage

I also thought so, but it is not localised as per the page language. @ravise5 has confirmed that.

**Pull request merged**
