### PR TITLE
FORMS-15104:Custom functions test cases for Playwright

### PR DESCRIPTION
**Pull request by pranay-tippa**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--aem-boilerplate-forms--adobe-rnd.hlx.live/
- After: https://forms-15104--aem-boilerplate-forms--adobe-rnd.hlx.page/

### CODE REVIEW

**Comment by ravise5** [comment]
@pranay-tippa please don't use JIRA IDs in commit messages.

**Review by ravise5 — CHANGES_REQUESTED** [review]
@pranay-tippa Please remove JIRA id's from commit messages.
Also lets start following the format recommended by @jalagari  in vega channel for commit messages.

**Comment by ravise5** [comment]
@pranay-tippa Also add a test case for the days custom function defined in function.js

**Comment by pranay-tippa** [comment]
This test is already exist in Unit test cases.

**Pull request closed without merging**
